[2025-09-01T08:21:16.260+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-09-01T08:21:04.563558+00:00 [queued]>
[2025-09-01T08:21:16.265+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load manual__2025-09-01T08:21:04.563558+00:00 [queued]>
[2025-09-01T08:21:16.265+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T08:21:16.282+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-09-01 08:21:04.563558+00:00
[2025-09-01T08:21:16.330+0000] {standard_task_runner.py:60} INFO - Started process 260 to run task
[2025-09-01T08:21:16.343+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load', 'manual__2025-09-01T08:21:04.563558+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpqm3d9lta']
[2025-09-01T08:21:16.356+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask load
[2025-09-01T08:21:16.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-01T08:21:16.575+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.load manual__2025-09-01T08:21:04.563558+00:00 [running]> on host f2eaf966b043
[2025-09-01T08:21:16.792+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T08:21:04.563558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T08:21:04.563558+00:00'
[2025-09-01T08:21:16.858+0000] {etl_pipeline.py:137} INFO - Reading processed file /tmp/etl_processed/processed_9f780e7d-6cce-4662-bfec-ef425d90c40e_applicants.csv
[2025-09-01T08:21:16.900+0000] {etl_pipeline.py:161} INFO - Inserting 20 rows into ClickHouse table applicants
[2025-09-01T08:21:16.931+0000] {etl_pipeline.py:164} ERROR - Failed to insert into ClickHouse: Code: 16.
DB::Exception: No such column applicant_id in table default.applicants (72514e27-acf8-4c40-b162-9390866d8fe6). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000010c92930
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b730698
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b730168
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000c2d627c
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000014ef4104
5. DB::InterpreterInsertQuery::execute() @ 0x0000000014ef8110
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001526e93c
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000015269e28
8. DB::TCPHandler::runImpl() @ 0x00000000165feec0
9. DB::TCPHandler::run() @ 0x000000001661aae4
10. Poco::Net::TCPServerConnection::start() @ 0x000000001b0f9e98
11. Poco::Net::TCPServerDispatcher::run() @ 0x000000001b0fa434
12. Poco::PooledThread::run() @ 0x000000001b0c03dc
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001b0be750
14. ? @ 0x000000000007d5b8
15. ? @ 0x00000000000e5edc
Traceback (most recent call last):
  File "/opt/airflow/dags/etl_pipeline.py", line 162, in perform_load
    client.execute(insert_sql, records)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 604, in process_insert_query
    sample_block = self.receive_sample_block()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 620, in receive_sample_block
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 16.
DB::Exception: No such column applicant_id in table default.applicants (72514e27-acf8-4c40-b162-9390866d8fe6). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000010c92930
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b730698
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b730168
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000c2d627c
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000014ef4104
5. DB::InterpreterInsertQuery::execute() @ 0x0000000014ef8110
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001526e93c
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000015269e28
8. DB::TCPHandler::runImpl() @ 0x00000000165feec0
9. DB::TCPHandler::run() @ 0x000000001661aae4
10. Poco::Net::TCPServerConnection::start() @ 0x000000001b0f9e98
11. Poco::Net::TCPServerDispatcher::run() @ 0x000000001b0fa434
12. Poco::PooledThread::run() @ 0x000000001b0c03dc
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001b0be750
14. ? @ 0x000000000007d5b8
15. ? @ 0x00000000000e5edc

[2025-09-01T08:21:16.935+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/etl_pipeline.py", line 162, in perform_load
    client.execute(insert_sql, records)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 376, in execute
    rv = self.process_insert_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 604, in process_insert_query
    sample_block = self.receive_sample_block()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 620, in receive_sample_block
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 16.
DB::Exception: No such column applicant_id in table default.applicants (72514e27-acf8-4c40-b162-9390866d8fe6). Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000010c92930
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000b730698
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b730168
3. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x000000000c2d627c
4. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000014ef4104
5. DB::InterpreterInsertQuery::execute() @ 0x0000000014ef8110
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x000000001526e93c
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x0000000015269e28
8. DB::TCPHandler::runImpl() @ 0x00000000165feec0
9. DB::TCPHandler::run() @ 0x000000001661aae4
10. Poco::Net::TCPServerConnection::start() @ 0x000000001b0f9e98
11. Poco::Net::TCPServerDispatcher::run() @ 0x000000001b0fa434
12. Poco::PooledThread::run() @ 0x000000001b0c03dc
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001b0be750
14. ? @ 0x000000000007d5b8
15. ? @ 0x00000000000e5edc


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 214, in run_load
    perform_load(processed_path=processed_path)
  File "/opt/airflow/dags/etl_pipeline.py", line 165, in perform_load
    raise RuntimeError(f"Load failed for {processed_path} into {CLICKHOUSE_TABLE}") from e
RuntimeError: Load failed for /tmp/etl_processed/processed_9f780e7d-6cce-4662-bfec-ef425d90c40e_applicants.csv into applicants
[2025-09-01T08:21:16.949+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=load, execution_date=20250901T082104, start_date=20250901T082116, end_date=20250901T082116
[2025-09-01T08:21:16.958+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task load (Load failed for /tmp/etl_processed/processed_9f780e7d-6cce-4662-bfec-ef425d90c40e_applicants.csv into applicants; 260)
[2025-09-01T08:21:16.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-01T08:21:17.057+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
