[2025-09-01T04:16:17.712+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: etl_pipeline.extract manual__2025-09-01T04:16:16.218856+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
